name: CI

on:
  pull_request:
  push:
    branches: [main]
jobs:
  Spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: codespell-project/codespell-problem-matcher@v1
    - name: Check Spelling
      run: nix develop --command codespell .

  Terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Terraform fmt
        run: nix-shell --run 'terraform fmt -check -recursive ./terraform'
      - name: Terraform init
        run: nix-shell --run 'terraform -chdir=./terraform init'
      - name: Terraform validate
        run: nix-shell --run 'terraform -chdir=./terraform validate -no-color'

  Nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - name: Check Formatting
      run: nix develop --command nixpkgs-fmt .

  Evaluate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - name: Evaluate ZFS
      run: nix-instantiate . -A images.zfs.x86_64-linux

  EditorConfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: greut/eclint-action@v0
